"""initial schema

Revision ID: 11d971e5ad58
Revises: 
Create Date: 2026-06-01 14:04:36.853668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11d971e5ad58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facebook_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_groups_facebook_id'), 'target_groups', ['facebook_id'], unique=True)
    op.create_table('raw_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('facebook_post_id', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('author_profile_url', sa.String(), nullable=True),
    sa.Column('author_facebook_id', sa.String(), nullable=True),
    sa.Column('post_text', sa.Text(), nullable=False),
    sa.Column('post_url', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reactions_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('comments_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['target_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_posts_author_facebook_id'), 'raw_posts', ['author_facebook_id'], unique=False)
    op.create_index(op.f('ix_raw_posts_facebook_post_id'), 'raw_posts', ['facebook_post_id'], unique=True)
    op.create_index(op.f('ix_raw_posts_group_id'), 'raw_posts', ['group_id'], unique=False)
    op.create_index(op.f('ix_raw_posts_processed'), 'raw_posts', ['processed'], unique=False)
    op.create_index(op.f('ix_raw_posts_scraped_at'), 'raw_posts', ['scraped_at'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_post_id', sa.UUID(), nullable=False),
    sa.Column('urgency_score', sa.Integer(), nullable=False),
    sa.Column('lead_type', sa.String(), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=False),
    sa.Column('suggested_comment', sa.Text(), nullable=True),
    sa.Column('suggested_dm', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(), server_default=sa.text("'new'"), nullable=False),
    sa.Column('marcus_notes', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_post_id'], ['raw_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_post_id')
    )
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    op.create_index(op.f('ix_leads_urgency_score'), 'leads', ['urgency_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_urgency_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_raw_posts_scraped_at'), table_name='raw_posts')
    op.drop_index(op.f('ix_raw_posts_processed'), table_name='raw_posts')
    op.drop_index(op.f('ix_raw_posts_group_id'), table_name='raw_posts')
    op.drop_index(op.f('ix_raw_posts_facebook_post_id'), table_name='raw_posts')
    op.drop_index(op.f('ix_raw_posts_author_facebook_id'), table_name='raw_posts')
    op.drop_table('raw_posts')
    op.drop_index(op.f('ix_target_groups_facebook_id'), table_name='target_groups')
    op.drop_table('target_groups')
    # ### end Alembic commands ###
