"""add scoring agent columns

Revision ID: 87a93200062f
Revises: b4f4fd55812e
Create Date: 2026-06-01 16:51:25.724025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a93200062f'
down_revision: Union[str, None] = 'b4f4fd55812e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('angle', sa.Text(), nullable=True))
    op.add_column('raw_posts', sa.Column('score_status', sa.String(), nullable=True))
    op.add_column('raw_posts', sa.Column('score_reasoning', sa.Text(), nullable=True))
    op.create_index(op.f('ix_raw_posts_score_status'), 'raw_posts', ['score_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_posts_score_status'), table_name='raw_posts')
    op.drop_column('raw_posts', 'score_reasoning')
    op.drop_column('raw_posts', 'score_status')
    op.drop_column('leads', 'angle')
    # ### end Alembic commands ###
