"""add filter status to raw_posts

Revision ID: b4f4fd55812e
Revises: 11d971e5ad58
Create Date: 2026-06-01 16:33:29.067599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f4fd55812e'
down_revision: Union[str, None] = '11d971e5ad58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_posts', sa.Column('filter_status', sa.String(), nullable=True))
    op.add_column('raw_posts', sa.Column('filter_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_raw_posts_filter_status'), 'raw_posts', ['filter_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_posts_filter_status'), table_name='raw_posts')
    op.drop_column('raw_posts', 'filter_reason')
    op.drop_column('raw_posts', 'filter_status')
    # ### end Alembic commands ###
