"""add scan_runs table

Revision ID: c295b72283ae
Revises: 87a93200062f
Create Date: 2026-06-01 17:38:00.663298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c295b72283ae'
down_revision: Union[str, None] = '87a93200062f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('groups_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('groups_completed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('posts_scraped', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('posts_filtered', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('posts_scored', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('leads_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scan_runs_single_running', 'scan_runs', ['status'], unique=True, postgresql_where=sa.text("status = 'running'"))
    op.create_index(op.f('ix_scan_runs_status'), 'scan_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_runs_status'), table_name='scan_runs')
    op.drop_index('ix_scan_runs_single_running', table_name='scan_runs', postgresql_where=sa.text("status = 'running'"))
    op.drop_table('scan_runs')
    # ### end Alembic commands ###
